server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: config-service
  profiles:
    active: native # local-storage
  cloud:
    config:
      server:
        native:
          search-locations: classpath://configurations

management:
  endpoints:
    web:
      exposure:
        include: health
